# -*- coding: utf-8 -*-
"""Stock Price Forecasting of Britania Using MA and ARMA Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQOrWPsqXeriksx_gm4hz_mDh0ieDBbh

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

import warnings
warnings.filterwarnings('ignore')

"""Load Dataset"""

df = pd.read_csv('/content/BRITANNIA.NS_stock_data.csv')

df.head()

"""Dataset Information"""

print(df.shape)

df.info()

df.isnull().sum()

"""Handle Date Column"""

df['Unnamed: 0'] = pd.to_datetime(df['Unnamed: 0'])

df.set_index('Unnamed: 0', inplace=True)

"""Remove Missing Values"""

df = df.dropna()

"""Select Close Price"""

series = df['close']

series.head()

"""Plot Closing Price"""

plt.figure(figsize=(12,5))

plt.plot(series)

plt.title("Britannia Industries Closing Price")
plt.xlabel("Date")
plt.ylabel("Close Price")

plt.show()

"""Train-Test Split"""

train_size = int(len(series)*0.80)

train = series[:train_size]

test = series[train_size:]

print("Train Size :", len(train))
print("Test Size :", len(test))

"""MA Model (q = 1 to 10)"""

results = []

for q in range(1,4):

    model = ARIMA(train,
                  order=(0,0,q))

    fit = model.fit()

    forecast = fit.forecast(
        steps=len(test)
    )

    rmse = np.sqrt(
        mean_squared_error(
            test,
            forecast
        )
    )

    mape = mean_absolute_percentage_error(
        test,
        forecast
    )

    results.append([
        q,
        rmse,
        mape
    ])

"""Result Table"""

result_df = pd.DataFrame(
    results,
    columns=[
        'MA_Order',
        'RMSE',
        'MAPE'
    ]
)

result_df

"""Best Model

✅ MA(3)

Because it has the lowest RMSE (3355.43) and lowest MAPE (0.8906).

Sort by RMSE
"""

result_df.sort_values(
    by='RMSE'
)

"""Select Best Model Automatically"""

best_q = result_df.loc[
    result_df['RMSE'].idxmin(),
    'MA_Order'
]

print("Best MA Order =", best_q)

"""Train Final Model"""

final_model = ARIMA(
    train,
    order=(0,0,int(best_q))
)

final_fit = final_model.fit()

forecast = final_fit.forecast(
    steps=len(test)
)

"""Forecast Plot"""

plt.figure(figsize=(14,6))

plt.plot(
    test.index,
    test,
    label='Actual'
)

plt.plot(
    test.index,
    forecast,
    label='Forecast'
)

plt.title(
    f'Britannia MA({best_q}) Forecast'
)

plt.legend()

plt.show()

"""Final Metrics"""

rmse = np.sqrt(
    mean_squared_error(
        test,
        forecast
    )
)

mape = mean_absolute_percentage_error(
    test,
    forecast
)

accuracy = 100 - (mape*100)

print("RMSE :", rmse)
print("MAPE :", mape)
print("Accuracy :", round(accuracy,2), "%")

"""Model Summary"""

print(final_fit.summary())

"""Run the ADF Test:"""

from statsmodels.tsa.stattools import adfuller

result = adfuller(series)

print("ADF Statistic:", result[0])
print("p-value:", result[1])

if result[1] < 0.05:
    print("Stationary")
else:
    print("Non-Stationary")

"""| Metric        | Value            |
| ------------- | ---------------- |
| ADF Statistic | 1.4334           |
| p-value       | 0.9973           |
| Result        | ❌ Non-Stationary |
=======
Since p-value > 0.05, the series is non-stationary.

Differencing
"""

series_diff = series.diff().dropna()

series_diff.head()

"""Plot Differenced Series"""

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.plot(series_diff)

plt.title("Britannia - First Differenced Series")
plt.show()

"""Run ADF Again"""

from statsmodels.tsa.stattools import adfuller

result = adfuller(series_diff)

print("ADF Statistic:", result[0])
print("p-value:", result[1])

if result[1] < 0.05:
    print("Stationary")
else:
    print("Non-Stationary")

"""| Metric        | Value        |
| ------------- | ------------ |
| ADF Statistic | -15.9521     |
| p-value       | 7.34 × 10⁻²⁹ |
| Result        | ✅ Stationary |

ARMA Model
"""

train_size = int(len(series_diff)*0.80)

train = series_diff[:train_size]
test = series_diff[train_size:]

print("Train:", len(train))
print("Test :", len(test))

"""ARMA Model Search"""

from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

results = []

for p in range(1,4):
    for q in range(1,4):

        print(f"Running ARMA({p},{q})")

        model = ARIMA(train, order=(p,0,q))

        fit = model.fit()

        forecast = fit.forecast(steps=len(test))

        rmse = np.sqrt(
            mean_squared_error(test, forecast)
        )

        results.append([p,q,rmse])

result_df = pd.DataFrame(
    results,
    columns=[
        "AR_Order",
        "MA_Order",
        "RMSE"
    ]
)

result_df.sort_values("RMSE")

"""| Model                        | RMSE      |
| ---------------------------- | --------- |
| MA(3) on raw data            | 3355.43   |
| ARMA(1,1) on stationary data | **51.93** |

=========

ARMA(1,1) has the lowest RMSE, so it is your best model.

Train Final ARMA(1,1)
"""

best_model = ARIMA(
    train,
    order=(1,0,1)
)

best_fit = best_model.fit()

print(best_fit.summary())

"""Forecast"""

forecast = best_fit.forecast(
    steps=len(test)
)

"""Plot Actual vs Forecast"""

import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))

plt.plot(
    test.index,
    test,
    label='Actual'
)

plt.plot(
    test.index,
    forecast,
    label='Forecast'
)

plt.title("ARMA(1,1) Forecast")

plt.legend()

plt.show()

"""Final Metrics"""

from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        test,
        forecast
    )
)

mape = mean_absolute_percentage_error(
    test,
    forecast
)

print("RMSE :", rmse)
print("MAPE :", mape)

"""Forecast Next 4 Days"""

future_forecast = best_fit.forecast(steps=4)

print(future_forecast)

future_forecast = best_fit.forecast(steps=4)

forecast_df = pd.DataFrame({
    "Forecast": future_forecast
})

print(forecast_df)

"""These are differenced values, not actual stock prices.

Convert Forecast Back to Actual Price

Get the last actual closing price:
"""

last_price = series.iloc[-1]

print(last_price)

"""Now convert:"""

future_diff = best_fit.forecast(steps=4)

future_price = []

current_price = series.iloc[-1]

for diff in future_diff:
    current_price = current_price + diff
    future_price.append(current_price)

future_price

"""| Day   | Forecasted Close Price (₹) |
| ----- | -------------------------: |
| Day 1 |                    4798.21 |
| Day 2 |                    4800.52 |
| Day 3 |                    4799.69 |
| Day 4 |                    4801.35 |

Interpretation
Day 1: Slight decrease
Day 2: Small increase
Day 3: Minor correction
Day 4: Increase again

Overall, the model predicts sideways movement around ₹4800 with very small daily fluctuations.

Create a Clean Forecast Table
"""

forecast_price_df = pd.DataFrame({
    "Day": ["Day 1", "Day 2", "Day 3", "Day 4"],
    "Forecasted Close Price": future_price
})

forecast_price_df

"""Plot Forecast"""

plt.figure(figsize=(8,4))

plt.plot(
    forecast_price_df["Day"],
    forecast_price_df["Forecasted Close Price"],
    marker='o'
)

plt.title("Britannia Next 4-Day Forecast (ARMA(1,1))")
plt.xlabel("Future Days")
plt.ylabel("Forecasted Close Price")

plt.grid(True)
plt.show()

"""| Stock Price |  RMSE | Interpretation    |
| ----------- | ----: | ----------------- |
| ₹4800       | ₹3355 | Very High Error ❌ |
| ₹4800       |  ₹500 | Moderate Error    |
| ₹4800       |  ₹100 | Good Error ✅      |
| ₹4800       |   ₹50 | Very Good Error ✅ |

==========

| Model     |    RMSE |
| --------- | ------: |
| MA(3)     | 3355.43 |
| ARMA(1,1) |   51.93 |

===========

ARMA reduced the error by about 3303 points.

=======

Percentage Error View

Approximate:


(3355/4800)x100 = 70%
	​

So MA predictions are off by roughly 70% of the stock price, which is very high.

=====

For ARMA:

4800
(51.93/4800)x100 = 1.08%
	​

Only about 1% error, which is much better.

===========

MA Thinking
Yesterday forecast was wrong by ₹2.
Use that error to improve tomorrow's forecast.
AR Thinking
Yesterday price was ₹4795.
Use previous prices to estimate tomorrow.
ARMA Thinking
Yesterday price was ₹4795
AND
Yesterday forecast error was ₹2

Use both information sources.

This is why ARMA is usually better.

| Step             | Result         |
| ---------------- | -------------- |
| Original Series  | Non-Stationary |
| ADF p-value      | 0.9972         |
| First Difference | Applied        |
| New ADF p-value  | 7.34e-29       |
| Best MA Model    | MA(3)          |
| Best ARMA Model  | ARMA(1,1)      |
| RMSE             | 51.93          |

| Step No | Process                         | Activity                                              | Output                             |
| ------- | ------------------------------- | ----------------------------------------------------- | ---------------------------------- |
| 1       | Data Collection                 | Collect historical Britannia stock price data         | Raw Dataset                        |
| 2       | Data Preprocessing              | Convert Date format, set index, handle missing values | Clean Dataset                      |
| 3       | Exploratory Data Analysis (EDA) | Plot stock price trend, histogram, boxplot            | Data Understanding                 |
| 4       | Stationarity Check              | Perform ADF Test                                      | Stationary / Non-Stationary Result |
| 5       | Log Transformation (Optional)   | Apply log transformation if variance is increasing    | Stabilized Variance                |
| 6       | Differencing                    | Remove trend from data                                | Stationary Series                  |
| 7       | ADF Test Again                  | Recheck stationarity after transformation             | Confirmed Stationary Data          |
| 8       | Build MA Models                 | Create MA(1), MA(2), MA(3) models                     | MA Forecasts                       |
| 9       | Evaluate MA Models              | Calculate RMSE for each MA model                      | Best MA Model Identified           |
| 10      | ACF & PACF Analysis             | Determine AR (p) and MA (q) values                    | ARMA Parameters                    |
| 11      | Build ARMA Model                | Train ARMA(p,q) model                                 | ARMA Forecast Model                |
| 12      | Forecast Future Prices          | Predict future Britannia stock prices                 | Forecast Values                    |
| 13      | Performance Evaluation          | Calculate RMSE and MAPE                               | Model Accuracy                     |
| 14      | Model Comparison                | Compare MA and ARMA results                           | Best Forecasting Model             |
| 15      | Final Conclusion                | Select model with lowest forecasting error            | Final Stock Forecast               |

| Phase                | Technique Used        | Purpose              |
| -------------------- | --------------------- | -------------------- |
| Data Preparation     | Cleaning & Formatting | Prepare dataset      |
| Time Series Analysis | ADF Test              | Check stationarity   |
| Data Transformation  | Log & Differencing    | Make data stationary |
| Forecasting Model 1  | Moving Average (MA)   | Baseline forecasting |
| Forecasting Model 2  | ARMA                  | Advanced forecasting |
| Evaluation           | RMSE, MAPE            | Measure accuracy     |
| Comparison           | MA vs ARMA            | Select best model    |
| Prediction           | Future Forecasting    | Predict stock prices |

###**Conclusion**

| S.No | Conclusion                                                                                                                                                                                                                    |
| ---- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1    | Historical stock price data of Britannia Industries Limited was successfully analyzed and transformed into a stationary time series using appropriate preprocessing techniques such as differencing and stationarity testing. |
| 2    | Moving Average models MA(1), MA(2), and MA(3) were developed and evaluated. Among them, **MA(3)** produced the lowest RMSE value (**3355.43**), indicating the best performance among the MA models.                          |
| 3    | The ARMA model was developed to capture both past stock price movements and previous forecast errors, providing a more comprehensive forecasting approach than the simple Moving Average model.                               |
| 4    | Based on forecasting accuracy and model comparison, the ARMA model is recommended for future Britannia stock price prediction, while MA(3) serves as an effective baseline forecasting model.                                 |
"""