# -*- coding: utf-8 -*-
"""Stock Price Forecasting of Asian Paints Using AutoRegressive (AR) Model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eLRSkepaKsQl7tuX2Q9q1Bx6tdsh6Oj

Import Libraries
"""

!pip install yfinance
import pandas as pd
import numpy as np
import datetime as dt

# from nsepy import get_history as gh # This library is causing SSL issues, switching to yfinance
import yfinance as yf

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

from statsmodels.tsa.ar_model import AutoReg

import matplotlib.pyplot as plt

"""Download Asian Paints Data"""

start = dt.datetime(2020,1,1)
end   = dt.datetime(2023,1,1)

# Using yfinance to download data as nsepy is encountering SSL errors
stk_data = yf.download(
    tickers='ASIANPAINT.NS',
    start=start,
    end=end
)

stk_data.head()

"""Select Required Columns"""

stk_data = stk_data[['Open','High','Low','Close']]

stk_data

"""Choose Close Price"""

column = "Close"

data = stk_data[[column]]

"""Close Price
=
Final market value of the stock
"""

from sklearn.preprocessing import MinMaxScaler
Ms = MinMaxScaler()
data1= Ms.fit_transform(stk_data[[column]])
print("Len:",data1.shape)

len(data1)

"""Train-Test Split

Split:

80% Training
20% Testing
"""

training_size = round(len(data1 ) * 0.80)
print(training_size)
X_train=data1[:training_size]
X_test=data1[training_size:]
print("X_train length:",X_train.shape)
print("X_test length:",X_test.shape)
y_train=data1[:training_size]
y_test=data1[training_size:]
print("y_train length:",y_train.shape)
print("y_test length:",y_test.shape)

"""Test multiple AR models.
Compare their performance.
Select the model with:
Lowest RMSE
Lowest MAPE
"""

from sklearn.metrics import mean_squared_error
from statsmodels.tsa.ar_model import AutoReg
import numpy as np # Import numpy for sqrt

trends = ['n','t','c','ct']
lags = [1,2,3,4]

for i in lags:

    for td in trends:

        model = AutoReg(
            X_train.flatten(),
            lags=i,
            trend=td
        )

        model_fit = model.fit()

        y_pred = model_fit.predict(
            start=len(X_train),
            end=len(data1)-1
        )

        print("Lag = {}, Trend = {}".format(i, td))

        mse = mean_squared_error(
            y_test.flatten(),
            y_pred
        )
        rmse = np.sqrt(mse) # Calculate RMSE by taking the square root of MSE

        mape = (
            abs(
                (y_test.flatten() - y_pred)
                / y_test.flatten()
            ).mean()
        ) * 100

        print("RMSE =", rmse)
        print("MAPE =", mape)
        print("********************")

"""How many stock prices did the model predict?"
"""

len(y_pred)

"""trains an AR(1) model with a constant and time trend (ct), generates predictions on the test data, and evaluates performance using RMSE and MAPE."""

i=1
td='ct'
model = AutoReg(X_train, lags=i,trend=td)
model_fit = model.fit()
# make prediction
y_pred= model_fit.predict(len(X_train), len(data1)-1)
#print(y_pred)
from sklearn.metrics import r2_score
import numpy as np # Import numpy for sqrt
mse_value=mean_squared_error(y_test,y_pred) # Calculate MSE
rmse=np.sqrt(mse_value) # Calculate RMSE

def rmsemape(y_true, y_pred):
    rmse_val = np.sqrt(mean_squared_error(y_true, y_pred))
    mape_val = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
    print(f"RMSE = {rmse_val}")
    print(f"MAPE = {mape_val}")

print("Lag={},Trend={}".format(i,td))
rmsemape(y_test,y_pred)
print("************")

"""The model uses 1 previous observation.
Includes constant and time trend.
Average prediction error ≈ 20.79%.
"""

import matplotlib.pyplot as plt

def graph(y_true, y_pred, label_true, label_pred, title, xlabel, ylabel):
    plt.figure(figsize=(12, 6))
    plt.plot(y_true, label=label_true)
    plt.plot(y_pred, label=label_pred)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()

graph(
    y_test,
    y_pred,
    "Actual",
    "Predicted",
    "AsianPaints-Close-AR-Norm",
    "Days",
    "Prices"
)

"""| Code                                 | Purpose                                        |
| ------------------------------------ | ---------------------------------------------- |
| `import matplotlib.pyplot as plt`    | Imports Matplotlib library for plotting graphs |
| `def graph(...)`                     | Creates a reusable graph function              |
| `plt.figure(figsize=(12,6))`         | Sets graph size to 12 × 6 inches               |
| `plt.plot(y_true, label=label_true)` | Plots actual stock prices                      |
| `plt.plot(y_pred, label=label_pred)` | Plots predicted stock prices                   |
| `plt.title(title)`                   | Adds graph title                               |
| `plt.xlabel(xlabel)`                 | Sets X-axis label                              |
| `plt.ylabel(ylabel)`                 | Sets Y-axis label                              |
| `plt.legend()`                       | Displays legend (Actual vs Predicted)          |
| `plt.show()`                         | Displays the graph                             |
| `graph(...)`                         | Calls the function and generates the graph     |

"""

len(data1)

"""total number of records (rows) in Asian Paints dataset.

There are 747 daily closing-price records available for Asian Paints from 2020–2023.
"""

y_test

"""y_test contains the actual test values after normalization.

| Code     | Purpose                                             |
| -------- | --------------------------------------------------- |
| `y_test` | Stores actual stock prices from the testing dataset |
====

are scaled values between 0 and 1 because of:
Ms = MinMaxScaler()
"""

rmsemape(y_test, y_pred)

"""For the Asian Paints AR model, RMSE is 0.1769 and MAPE is 18.70%, indicating that the model can reasonably forecast stock price movements.

which is generally considered reasonable/good for stock-price forecasting.

| RMSE Value       | Interpretation               |
| ---------------- | ---------------------------- |
| RMSE = 0         | Perfect prediction           |
| RMSE < 0.1       | Excellent                    |
| 0.1 ≤ RMSE < 0.2 | Very Good                    |
| 0.2 ≤ RMSE < 0.5 | Good                         |
| 0.5 ≤ RMSE < 1.0 | Acceptable                   |
| RMSE > 1.0       | Poor (depends on data scale) |

| Variable | Meaning          |
| -------- | ---------------- |
| `y_test` | Actual values    |
| `y_pred` | Predicted values |

convert normalized stock prices back to original Asian Paints prices
"""

import pandas as pd

def conversionSingle(data_array, columns):
    # Reshape if necessary to ensure it's 2D for inverse_transform
    if data_array.ndim == 1:
        data_array = data_array.reshape(-1, 1)

    # Inverse transform the data using the fitted MinMaxScaler (Ms)
    original_scale_data = Ms.inverse_transform(data_array)

    # Create a DataFrame with the original column names
    df = pd.DataFrame(original_scale_data, columns=columns)
    return df

asianPaints_TestNormTable = conversionSingle(
    y_test,
    [column]
)

"""| Code                                         | Purpose                                                   |
| -------------------------------------------- | --------------------------------------------------------- |
| `import pandas as pd`                        | Imports Pandas library for DataFrame creation             |
| `def conversionSingle(data_array, columns):` | Defines a reusable conversion function                    |
| `if data_array.ndim == 1:`                   | Checks whether input data is 1-dimensional                |
| `data_array.reshape(-1,1)`                   | Converts 1D array into 2D format required by MinMaxScaler |
| `Ms.inverse_transform(data_array)`           | Converts normalized values back to original stock prices  |
| `pd.DataFrame(...)`                          | Creates a DataFrame from the converted values             |
| `columns=columns`                            | Assigns the original column name (e.g., Close)            |
| `return df`                                  | Returns the converted DataFrame                           |

"""

asianPaints_TestNormTable

print(y_test[0])

Ms.inverse_transform(y_test[:1])

print(y_test[1])

Ms.inverse_transform(y_test[:2])

actual_stock_price_test_ori=Ms.inverse_transform(asianPaints_TestNormTable)

"""| Code                          | Purpose                                           |
| ----------------------------- | ------------------------------------------------- |
| `Ms`                          | Trained MinMaxScaler object                       |
| `inverse_transform()`         | Converts normalized values back to original scale |
| `asianPaints_TestNormTable`   | Input normalized stock-price data                 |
| `actual_stock_price_test_ori` | Stores original stock prices after conversion     |

"""

actual_stock_price_test_ori

"""| Code                          | Purpose                                  |
| ----------------------------- | ---------------------------------------- |
| `actual_stock_price_test_ori` | Displays the converted stock prices      |
| Output                        | Original Asian Paints closing prices (₹) |

"""

actual_stock_price_test_oriA=conversionSingle(actual_stock_price_test_ori,[column])

"""| Code                           | Purpose                                            |
| ------------------------------ | -------------------------------------------------- |
| `conversionSingle()`           | Converts NumPy array into DataFrame                |
| `actual_stock_price_test_ori`  | Original stock prices after inverse transformation |
| `[column]`                     | Assigns column name (`Close`)                      |
| `actual_stock_price_test_oriA` | Stores actual stock prices in DataFrame format     |
========

Converts actual stock prices into a structured DataFrame for graph plotting and comparison.
"""

print(stk_data[['Close']].head())
print(stk_data[['Close']].describe())

"""| Statistic |   Value | Meaning             |
| --------- | ------: | ------------------- |
| count     |     747 | Total records       |
| mean      | 2541.24 | Average stock price |
| std       |  591.72 | Standard deviation  |
| min       | 1430.82 | Lowest price        |
| 25%       | 1943.51 | First quartile      |
| 50%       | 2735.19 | Median price        |
| 75%       | 3028.51 | Third quartile      |
| max       | 3458.51 | Highest price       |

| Code                  | Purpose                    |
| --------------------- | -------------------------- |
| `stk_data[['Close']]` | Selects Close price column |
| `.head()`             | Displays first 5 records   |
===

| Code          | Purpose                                       |
| ------------- | --------------------------------------------- |
| `.describe()` | Generates statistical summary of Close prices |
"""

column = "Close"

data1 = stk_data[[column]]

from sklearn.preprocessing import MinMaxScaler

Ms = MinMaxScaler()

data1 = Ms.fit_transform(data1)

"""| Code                                             | Purpose                                                   |
| ------------------------------------------------ | --------------------------------------------------------- |
| `column = "Close"`                               | Selects the Close price column from Asian Paints dataset  |
| `data1 = stk_data[[column]]`                     | Creates a new dataset containing only Close prices        |
| `from sklearn.preprocessing import MinMaxScaler` | Imports MinMaxScaler for normalization                    |
| `Ms = MinMaxScaler()`                            | Creates MinMaxScaler object                               |
| `Ms.fit_transform(data1)`                        | Learns min/max values and normalizes data between 0 and 1 |
| `data1 = ...`                                    | Stores normalized values in `data1`                       |

==========
| Without Normalization        | With Normalization       |
| ---------------------------- | ------------------------ |
| Large values (₹1700–₹3400)   | Values between 0 and 1   |
| Training may be slower       | Faster model training    |
| Difficult to compare scales  | Uniform scale            |
| Higher numerical instability | Better model performance |
========

The Close price column is selected and normalized using MinMaxScaler. The scaler converts all stock prices into the range 0 to 1 using the minimum and maximum values of the dataset. This improves model training efficiency and ensures that all observations are on the same scale before applying the AutoRegressive model.
"""

print(Ms.data_min_)
print(Ms.data_max_)

"""





| Code           | Purpose                                                 |
| -------------- | ------------------------------------------------------- |
| `Ms.data_min_` | Displays the minimum stock price used for normalization |
| `Ms.data_max_` | Displays the maximum stock price used for normalization |
"""

actual_stock_price_test_ori = Ms.inverse_transform(y_test)

print(actual_stock_price_test_ori[:5])

"""| Code                          | Purpose                                            |
| ----------------------------- | -------------------------------------------------- |
| `y_test`                      | Contains normalized test stock prices              |
| `Ms.inverse_transform()`      | Converts normalized values back to original prices |
| `actual_stock_price_test_ori` | Stores actual stock prices in ₹                    |
| `[:5]`                        | Displays first 5 records                           |

============

| Before Inverse Transform | After Inverse Transform |
| ------------------------ | ----------------------- |
| 0.6451                   | ₹2738.90                |
| 0.6525                   | ₹2753.97                |
| 0.6491                   | ₹2747.09                |

"""

import pandas as pd
import matplotlib.pyplot as plt

# Define the graph function locally, as stockFunctions was not found previously
def graph(y_true, y_pred, label_true, label_pred, title, xlabel, ylabel):
    plt.figure(figsize=(12, 6))
    plt.plot(y_true, label=label_true)
    plt.plot(y_pred, label=label_pred)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.legend()
    plt.show()

actual_stock_price_test_oriA = pd.DataFrame(
    actual_stock_price_test_ori,
    columns=[column]
)

# Inverse transform y_pred to get predicted_stock_price_test_ori
predicted_stock_price_test_ori = Ms.inverse_transform(y_pred.reshape(-1, 1)) # Reshape to 2D if necessary

predicted_stock_price_test_oriP = pd.DataFrame(
    predicted_stock_price_test_ori,
    columns=[column]
)

graph(
    actual_stock_price_test_oriA,
    predicted_stock_price_test_oriP,
    "Actual",
    "Predicted",
    "AsianPaints-Close-AR-Ori",
    "Days",
    "Prices"
)

rmsemape(actual_stock_price_test_oriA,predicted_stock_price_test_oriP)

forecast=model_fit.predict(len(data1), len(data1)+3)

forecast

fTestNormTable = conversionSingle(forecast, ["Closefore"])
forecast_stock_price_test_ori = fTestNormTable.values
forecast_stock_price_test_oriF = fTestNormTable

forecast_stock_price_test_oriF

forecast_stock_price_test_oriF.to_csv("CloseAR.csv",index=False)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.plot(actual_stock_price_test_oriA[116:145], color = 'blue', label="Actual")
plt.plot(forecast_stock_price_test_oriF, color = 'red', label ="Predicted")

trends=['c']
lags=[1,2,3,4]

for i in lags:

    model = AutoReg(
        X_train.flatten(),
        lags=i,
        trend='c'
    )

    model_fit = model.fit()

    y_pred = model_fit.predict(
        len(X_train),
        len(data1)-1
    )

    print("Lag =", i)

    rmsemape(
        y_test.flatten(),
        y_pred
    )

    print("****************")

i = 1
td = 'c'

model = AutoReg(
    X_train.flatten(),
    lags=i,
    trend=td
)

model_fit = model.fit()

"""Generate Predictions"""

y_pred = model_fit.predict(
    start=len(X_train),
    end=len(data1)-1
)

"""Check RMSE and MAPE"""

print("Lag={}, Trend={}".format(i, td))
rmsemape(y_test.flatten(), y_pred)

"""Convert Actual Prices"""

actual_stock_price_test_ori = Ms.inverse_transform(y_test)

import pandas as pd

actual_stock_price_test_oriA = pd.DataFrame(
    actual_stock_price_test_ori,
    columns=[column]
)

actual_stock_price_test_oriA.head()

"""Convert Predicted Prices"""

predicted_stock_price_test_ori = Ms.inverse_transform(
    y_pred.reshape(-1,1)
)

predicted_stock_price_test_oriP = pd.DataFrame(
    predicted_stock_price_test_ori,
    columns=[column]
)

predicted_stock_price_test_oriP.head()

"""Actual vs Predicted Graph"""

graph(
    actual_stock_price_test_oriA,
    predicted_stock_price_test_oriP,
    "Actual",
    "Predicted",
    "AsianPaints-Close-AR-Ori",
    "Days",
    "Prices"
)

"""Forecast Next 4 Days"""

forecast = model_fit.predict(
    len(data1),
    len(data1)+3
)

forecast

"""Convert Forecast Back"""

forecast_stock_price_test_ori = Ms.inverse_transform(
    forecast.reshape(-1,1)
)

forecast_stock_price_test_oriF = pd.DataFrame(
    forecast_stock_price_test_ori,
    columns=["Closefore"]
)

forecast_stock_price_test_oriF

forecast_stock_price_test_oriF

"""| Predicted                   | Forecast                       |
| --------------------------- | ------------------------------ |
| Predicts test data          | Predicts future data           |
| Actual values available     | Actual values unavailable      |
| Used for evaluation         | Used for future estimation     |
| RMSE/MAPE can be calculated | RMSE/MAPE cannot be calculated |
| `y_pred`                    | `forecast`                     |

Save Forecast CSV
"""

forecast_stock_price_test_oriF.to_csv(
    "AsianPaints_Close_AR.csv",
    index=False
)

"""Plot Forecast Graph"""

import matplotlib.pyplot as plt

recent_actual = actual_stock_price_test_oriA.tail(10)

plt.figure(figsize=(10,5))

plt.plot(
    range(10),
    recent_actual.iloc[:,0].values,
    marker='o',
    label='Actual'
)

plt.plot(
    range(10,14),
    forecast_stock_price_test_oriF["Closefore"].values,
    marker='o',
    label='Forecast'
)

plt.title("Asian Paints Stock Price Forecast using AR")
plt.xlabel("Days")
plt.ylabel("Stock Price (₹)")
plt.legend()
plt.grid(True)

plt.show()

"""Final Result Cell"""

print("Future Forecasted Prices for Asian Paints")
print()

print(forecast_stock_price_test_oriF)