# -*- coding: utf-8 -*-
"""TimeSeries_Stationarity-pre-processing and stationarity checking phase

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xbFgRQ1NiR2N75lReexnfiq4TfpN-K2

Mount Google Drive

Connects Google Colab with Google Drive.
"""

from google.colab import drive
drive.mount('/content/drive')

"""Move to Working Directory

Changes current directory to the folder containing the dataset.
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks

"""Load Dataset

Reads CSV file.
Converts Date column into datetime format.
Sets Date as index.
"""

import pandas as pd
dataset=pd.read_csv("Tatacoffee13_21.csv", parse_dates=['Date'], index_col='Date')

dataset

"""Create Continuous Date Range

Creates all calendar dates between start and end date.
"""

#Start date and end_date
from datetime import date, timedelta
import pandas as pd
start_date = pd.to_datetime("2013-01-01")
end_date = pd.to_datetime("2019-02-04") - timedelta(days=1) #Excluding last

#List of all dates
all_date = pd.date_range(start_date, end_date, freq='d')

all_date

"""Assign New Date Index

Replaces existing index with continuous daily dates.
"""

dummyDate=dataset

dummyDate.index=all_date

dummyDate

#DateIndex.index=pd.to_datetime(dataset["Date"],infer_datetime_format=True)

"""Plot Closing Price

Visual inspection for:

Trend
Seasonality
Sudden changes
"""

import matplotlib.pyplot as plt
plt.plot(dataset["Close"])

print(dummyDate.index)
print(type(dummyDate.index))

"""Seasonal Decomposition (Multiplicative)

Decomposes series into:

Observed=Trend×Seasonal×Residual

Shows:

Original Series
Trend
Seasonality
Residual
"""

from pandas import read_csv
from matplotlib import pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(dummyDate["Close"], model='multiplicative')
plt.figure(figsize=(16,5))
result.plot()
plt.show()

"""Seasonal Decomposition (Additive)

Formula:

Observed=Trend+Seasonal+Residual

Used when seasonal fluctuations remain constant.
"""

from pandas import read_csv
from matplotlib import pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
result = seasonal_decompose(dummyDate["Close"], model='additive')
plt.figure(figsize=(16,5))
result.plot()
plt.show()

"""ADF Test (Stationarity Test)"""

# ADF Test
# Function to print out results in customised manner
from statsmodels.tsa.stattools import adfuller
def adf_test(timeseries,df,pollutant):
    plt.figure(figsize=(16,5))
    # Plot the data
    # ADF Test
    # Function to print out results in customised manner
    from statsmodels.tsa.stattools import adfuller
    print ('Results of Dickey-Fuller Test:')
    dftest = adfuller(timeseries, autolag='AIC')
    dfoutput = pd.Series(dftest[0:4], index=['Test Statistic','p-value','#Lags Used','Number of Observations Used'])
    for key,value in dftest[4].items():
        dfoutput['Critical Value (%s)'%key] = value
    print (dfoutput)
    ans=dfoutput
    print("Condition:")
    print("p-value<=0.05-->Accept Alternate Hypothesis")
    print("p-value>0.05-->Accept Null Hypothesis")
    if(ans['Test Statistic']<ans["Critical Value (1%)"] or ans['Test Statistic']<ans["Critical Value (5%)"] or ans['Test Statistic']<ans["Critical Value (10%)"] and ans["p-value"]<0.05):
        print("Condition: statictic < any critical value and p-value <0.05 to reject null hypothsis")
        print("Reject null hypothesis:Non Stationarity")
        print("Accept Alternate hypothesis:Staionarity ")
        message="Stationarity based on ADF"
    else:
        print("Condition: statictic < any critical value and p-value <0.05 to reject null hypothsis")
        print("Accept null hypothesis:Non Stationarity" )
        print("Reject Alternate hypothesis:Staionarity ")
        message="Non-stationarity based on ADF"

    plt.plot(df.index, df[pollutant], label = pollutant)
    plt.legend(loc='best')
    plt.title("{}_{}_2013 to 2021".format(message,pollutant))
    plt.savefig("{}_ADH.png".format(pollutant))
    plt.show()

    return message

# Call the function and run the test

"""| Line No | Code                                             | Explanation                         | Use                                             |
| ------- | ------------------------------------------------ | ----------------------------------- | ----------------------------------------------- |
| 1       | `from statsmodels.tsa.stattools import adfuller` | Imports ADF Test function.          | Used to check stationarity of time series data. |
| 2       | `def adf_test(timeseries,df,pollutant):`         | Creates custom function.            | Reusable function for multiple columns.         |
| 3       | `plt.figure(figsize=(16,5))`                     | Creates graph area.                 | Used to visualize the time series.              |
| 4       | `print('Results of Dickey-Fuller Test:')`        | Prints heading.                     | Makes output easy to understand.                |
| 5       | `dftest = adfuller(timeseries, autolag='AIC')`   | Runs ADF test.                      | Determines Stationary or Non-Stationary data.   |
| 6       | `pd.Series(dftest[0:4],...)`                     | Stores ADF results in table format. | Makes results readable.                         |
| 7       | `for key,value in dftest[4].items():`            | Loops through critical values.      | Retrieves 1%, 5%, and 10% significance levels.  |
| 8       | `dfoutput['Critical Value (%s)'%key] = value`    | Adds critical values.               | Used for hypothesis testing.                    |
| 9       | `print(dfoutput)`                                | Displays complete results.          | Helps in decision making.                       |
| 10      | `ans=dfoutput`                                   | Stores output.                      | Simplifies later condition checking.            |
| 11      | `print("Condition:")`                            | Prints rules.                       | Helps users interpret output.                   |
| 12      | `print("p-value<=0.05...")`                      | Shows Stationary condition.         | Decision guidance.                              |
| 13      | `print("p-value>0.05...")`                       | Shows Non-Stationary condition.     | Decision guidance.                              |

| Output                      | Explanation                   | Use                           |
| --------------------------- | ----------------------------- | ----------------------------- |
| Test Statistic              | Calculated ADF value          | Compared with Critical Values |
| p-value                     | Probability value             | Main decision factor          |
| #Lags Used                  | Number of lagged observations | Improves test accuracy        |
| Number of Observations Used | Records used in test          | Indicates sample size         |
| Critical Value (1%)         | Threshold at 99% confidence   | Hypothesis testing            |
| Critical Value (5%)         | Threshold at 95% confidence   | Most commonly used            |
| Critical Value (10%)        | Threshold at 90% confidence   | Less strict testing           |

====

| Code                                      | Explanation   | Use                            |
| ----------------------------------------- | ------------- | ------------------------------ |
| `Accept null hypothesis`                  | Accept H₀     | Data is non-stationary         |
| `Reject Alternate hypothesis`             | Reject H₁     | Data is not stationary         |
| `message="Non-stationarity based on ADH"` | Stores result | Used in graph title and output |
========

| Code                                | Explanation            | Use                          |
| ----------------------------------- | ---------------------- | ---------------------------- |
| `plt.plot(df.index, df[pollutant])` | Plots time series data | Visual trend analysis        |
| `plt.legend(loc='best')`            | Shows legend           | Identifies plotted variable  |
| `plt.title(...)`                    | Creates dynamic title  | Displays stationarity result |
| `plt.savefig(...)`                  | Saves graph            | Documentation and reporting  |
| `plt.show()`                        | Displays graph         | Visual inspection            |
| `return message`                    | Returns result         | Can be reused in code        |

ADF Test (Stationarity Test) Rule

| p-value | Result         |
| ------- | -------------- |
| ≤ 0.05  | Stationary     |
| > 0.05  | Non-Stationary |
"""

adf_test(dataset["Close"],dataset,"Close")

"""The graph shows stock closing prices over time. Although the series visually shows large changes, the ADF test indicates stationarity because p-value < 0.05 and the test statistic is more negative than the critical value.

| Component | Meaning                       |
| --------- | ----------------------------- |
| X-Axis    | Date (2013–2021)              |
| Y-Axis    | Close Price                   |
| Blue Line | Stock Closing Price           |
| Title     | ADF Test Result + Column Name |

========

| Phase   | Period            | Close Price Range (Approx.) | Observation                                   | Interpretation                           |
| ------- | ----------------- | --------------------------- | --------------------------------------------- | ---------------------------------------- |
| Phase 1 | 2013 – Early 2014 | 1400 – 1650                 | Prices fluctuate at a high level              | High mean and high variance              |
| Phase 2 | 2014 – 2015       | 1600 → 1000                 | Sharp downward drop observed                  | Structural break or major market event   |
| Phase 3 | 2015 – 2021       | 80 – 180                    | Prices move within a relatively smaller range | More stable behavior with lower variance |

=======

ACF and PACF

ACF

Measures:

Correlation(Yt​,Yt−k​)

Used for MA(q).	​

=========

PACF

Measures direct relationship after removing intermediate lags.

Used for AR(p).
"""

from statsmodels.tsa.stattools import acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

fig, axes = plt.subplots(1,2,figsize=(16,3), dpi= 100)
plot_acf(dataset.Close.tolist(), lags=50, ax=axes[0])
plot_pacf(dataset.Close.tolist(), lags=50, ax=axes[1])

"""Left Graph → ACF (Autocorrelation Function)
Right Graph → PACF (Partial Autocorrelation Function)

========

| Graph   | Observation                      | Conclusion                       |
| ------- | -------------------------------- | -------------------------------- |
| ACF     | Slow decay from 1.0 to 0.85      | Strong autocorrelation           |
| ACF     | Significant across all lags      | Long memory                      |
| PACF    | Large spike at Lag 1             | AR(1) behavior                   |
| PACF    | Remaining lags near zero         | Direct influence only from Lag 1 |
| Overall | Strong dependence on past values | Forecasting possible             |

ACF Line Plot

Shows correlation across lag values
"""

plt.plot(acf(dataset["Close"],nlags=50))

"""| Lag | Correlation (Approx.) | Observation                      |
| --- | --------------------- | -------------------------------- |
| 0   | 1.00                  | Perfect correlation with itself  |
| 10  | 0.97                  | Very strong positive correlation |
| 20  | 0.94                  | Strong positive correlation      |
| 30  | 0.90                  | Strong positive correlation      |
| 40  | 0.87                  | Strong positive correlation      |
| 50  | 0.85                  | Strong positive correlation      |

============


| Question                          | Answer                                                                     |
| --------------------------------- | -------------------------------------------------------------------------- |
| What does the ACF Line Plot show? | It shows correlation between the current value and previous lag values.    |
| What do you observe?              | Correlation remains very high and decreases slowly from 1.0 to about 0.85. |
| What does slow decay indicate?    | Strong autocorrelation and long memory.                                    |
| What model is suggested?          | AR(1) or ARIMA(1,d,0).                                                     |

============

The ACF line plot shows a slow decline from 1.0 to 0.85 across 50 lags, indicating very strong autocorrelation, long memory, and suitability for AR-based forecasting models.

PACF Line Plot

Helps identify AR order.
"""

plt.plot(pacf(dataset["Close"],nlags=50))

"""Partial Autocorrelation Function (PACF).

PACF measures the direct relationship between the current value and a previous lag after removing the effects of intermediate lags.

Example:

Today Price ← Yesterday Price ← Day Before Yesterday

PACF checks only the direct effect.

==========

| Observation           | Meaning                         |
| --------------------- | ------------------------------- |
| Lag 1 very high       | Strong direct influence         |
| Remaining lags near 0 | No significant direct influence |
| Sharp cutoff          | AR process present              |
| No repeating spikes   | No obvious seasonality          |

| Graph | Observation        | Suggestion |
| ----- | ------------------ | ---------- |
| ACF   | Slow decay         | AR process |
| PACF  | Cutoff after Lag 1 | AR(1)      |

===========

The PACF plot shows a strong spike at Lag 1 and near-zero values afterward, indicating that the current Close Price is mainly influenced by the immediately previous Close Price, suggesting an AR(1) process.

Lag Plot

Checks autocorrelation visually.

| Shape         | Meaning                |
| ------------- | ---------------------- |
| Straight Line | Strong autocorrelation |
| Random Cloud  | Weak autocorrelation   |

==========
"""

from pandas.plotting import lag_plot
lag_plot(dataset["Close"],lag=1)

"""| Axis   | Meaning                        |
| ------ | ------------------------------ |
| X-Axis | Current Value y(t)             |
| Y-Axis | Next/Previous Lag Value y(t+1) |
| Dot    | One observation pair           |

==========

| Observation No | What You See in Graph                                                         | Interpretation                                                                                     | Conclusion                               |
| -------------- | ----------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------- | ---------------------------------------- |
| Observation 1  | Points form a clear diagonal/straight-line pattern instead of a random cloud. | Current Close Price is strongly related to the previous Close Price.                               | ✅ Strong Autocorrelation                 |
| Observation 2  | Three distinct clusters/groups of points are visible.                         | The stock price moved through different price ranges (high, medium, low) during different periods. | ✅ Different Price Regimes / Phases Exist |
| Observation 3  | Very few isolated points are away from the main clusters.                     | Sudden changes or structural breaks occurred in the time series.                                   | ✅ Possible Outliers or Market Events     |

===========

The lag plot shows a strong diagonal pattern with three distinct clusters, indicating strong autocorrelation, clear historical dependence, and different price regimes in the stock series.

## Forecastability

### Apen small- Forecastability is possible
### Spen Small-Forecastability is possible

Approximate Entropy (ApEn)

Measures randomness.

| Value | Meaning      |
| ----- | ------------ |
| Small | Forecastable |
| Large | Random       |
"""

def ApEn(U, m, r):
    """Compute Aproximate entropy"""
    def _maxdist(x_i, x_j):
        return max([abs(ua - va) for ua, va in zip(x_i, x_j)])

    def _phi(m):
        x = [[U[j] for j in range(i, i + m - 1 + 1)] for i in range(N - m + 1)]
        C = [len([1 for x_j in x if _maxdist(x_i, x_j) <= r]) / (N - m + 1.0) for x_i in x]
        return (N - m + 1.0)**(-1) * sum(np.log(C))

    N = len(U)
    return abs(_phi(m+1) - _phi(m))

import numpy as np
print(ApEn(dataset["Close"], m=2, r=0.2*np.std(dataset["Close"])))

"""| ApEn Value | Interpretation      |
| ---------- | ------------------- |
| Near 0     | Highly predictable  |
| 0.1 - 0.5  | Moderate complexity |
| > 1        | Highly random       |

===========

0.0274 ≈ 0

✅ Very low randomness

✅ Strong underlying pattern exists

✅ Data points are highly similar to neighboring observations

✅ Time series is predictable

✅ Suitable for forecasting models such as:

ARIMA
SARIMA
Holt-Winters
Prophet
LSTM

Sample Entropy (SampEn)

Measures complexity.
| Value | Meaning     |
| ----- | ----------- |
| Small | Predictable |
| Large | Random      |
"""

def SampEn(U, m, r):
    """Compute Sample entropy"""
    def _maxdist(x_i, x_j):
        return max([abs(ua - va) for ua, va in zip(x_i, x_j)])

    def _phi(m):
        x = [[U[j] for j in range(i, i + m - 1 + 1)] for i in range(N - m + 1)]
        C = [len([1 for j in range(len(x)) if i != j and _maxdist(x[i], x[j]) <= r]) for i in range(len(x))]
        return sum(C)

    N = len(U)
    return -np.log(_phi(m+1) / _phi(m))

print(SampEn(dataset["Close"], m=2, r=0.2*np.std(dataset["Close"])))

"""| SampEn Value | Interpretation                         |
| ------------ | -------------------------------------- |
| Near 0       | Highly predictable                     |
| 0.1 – 1.0    | Moderate complexity                    |
| > 1.0        | Highly random                          |
| > 2.0        | Very complex and difficult to forecast |

===========

0.03987 ≈ 0

✅ Very low complexity

✅ Very low randomness

✅ Strong repeating patterns exist

✅ High predictability

✅ Suitable for forecasting models

| Step No | Topic                        | Code/Function                                     | Purpose                           | Output/Conclusion           |
| ------- | ---------------------------- | ------------------------------------------------- | --------------------------------- | --------------------------- |
| 1       | Mount Drive                  | `drive.mount()`                                   | Connect Google Drive              | Access dataset              |
| 2       | Change Directory             | `%cd`                                             | Navigate to dataset folder        | Working directory set       |
| 3       | Load Dataset                 | `pd.read_csv()`                                   | Read stock data                   | DataFrame created           |
| 4       | Create Date Range            | `pd.date_range()`                                 | Generate continuous dates         | Daily date index            |
| 5       | Assign Index                 | `dummyDate.index=all_date`                        | Replace date index                | Continuous time series      |
| 6       | Time Series Plot             | `plt.plot()`                                      | Visualize stock prices            | Trend identification        |
| 7       | Multiplicative Decomposition | `seasonal_decompose(..., model='multiplicative')` | Extract Trend, Seasonal, Residual | Check seasonality           |
| 8       | Additive Decomposition       | `seasonal_decompose(..., model='additive')`       | Alternative decomposition         | Check seasonality           |
| 9       | ADF Test                     | `adfuller()`                                      | Test stationarity                 | Stationary / Non-stationary |
| 10      | ACF Plot                     | `plot_acf()`                                      | Measure autocorrelation           | MA(q) identification        |
| 11      | PACF Plot                    | `plot_pacf()`                                     | Measure partial autocorrelation   | AR(p) identification        |
| 12      | ACF Values                   | `acf()`                                           | Numerical correlation values      | Lag relationship            |
| 13      | PACF Values                  | `pacf()`                                          | Numerical partial correlation     | AR order detection          |
| 14      | Lag Plot                     | `lag_plot()`                                      | Visual autocorrelation check      | Pattern detection           |
| 15      | Approximate Entropy          | `ApEn()`                                          | Measure randomness                | Forecastability check       |
| 16      | Sample Entropy               | `SampEn()`                                        | Measure complexity                | Forecastability check       |

| Analysis                  | Function Used          | Result Meaning                |
| ------------------------- | ---------------------- | ----------------------------- |
| Trend Detection           | Time Series Plot       | Upward/Downward movement      |
| Seasonality Detection     | Seasonal Decomposition | Repeating patterns            |
| Stationarity Check        | ADF Test               | Required for ARIMA            |
| Autocorrelation Check     | ACF                    | Dependence on previous values |
| Partial Correlation Check | PACF                   | Direct lag influence          |
| Randomness Check          | Approximate Entropy    | Predictability                |
| Complexity Check          | Sample Entropy         | Forecastability               |

Project Conclusion

| Metric                     | Value  | Interpretation           |
| -------------------------- | ------ | ------------------------ |
| Approximate Entropy (ApEn) | 0.0274 | Low Randomness           |
| Sample Entropy (SampEn)    | 0.0399 | Low Complexity           |
| Forecastability            | High   | Suitable for Forecasting |

===========

The Tata Coffee closing-price time series exhibits low randomness, low complexity, and high predictability. Therefore, it is a strong candidate for forecasting using ARIMA, SARIMA, Prophet, XGBoost, and LSTM models.
"""